pip install bluepy
Collecting bluepy
  Downloading bluepy-1.3.0.tar.gz (217 kB)
     |████████████████████████████████| 217 kB 1.0 MB/s 
Using legacy 'setup.py install' for bluepy, since package 'wheel' is not installed.
Installing collected packages: bluepy
    Running setup.py install for bluepy ... error
    ERROR: Command errored out with exit status 1:
     command: /Users/sebastian/zmk-config-corne-beekeeb/battery_reporter/env/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/57/x0b9lln16kqfwvd_m3xb97rm0000gn/T/pip-install-0vfax9e_/bluepy_94cc612fb75249e39668b35fe40eb5fa/setup.py'"'"'; __file__='"'"'/private/var/folders/57/x0b9lln16kqfwvd_m3xb97rm0000gn/T/pip-install-0vfax9e_/bluepy_94cc612fb75249e39668b35fe40eb5fa/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/57/x0b9lln16kqfwvd_m3xb97rm0000gn/T/pip-record-p4bm7m99/install-record.txt --single-version-externally-managed --compile --install-headers /Users/sebastian/zmk-config-corne-beekeeb/battery_reporter/env/include/site/python3.9/bluepy
         cwd: /private/var/folders/57/x0b9lln16kqfwvd_m3xb97rm0000gn/T/pip-install-0vfax9e_/bluepy_94cc612fb75249e39668b35fe40eb5fa/
    Complete output (13 lines):
    /Users/sebastian/zmk-config-corne-beekeeb/battery_reporter/env/lib/python3.9/site-packages/setuptools/dist.py:717: UserWarning: Usage of dash-separated 'description-file' will not be supported in future versions. Please use the underscore name 'description_file' instead
      warnings.warn(
    running install
    running build
    running build_py
    Working dir is /private/var/folders/57/x0b9lln16kqfwvd_m3xb97rm0000gn/T/pip-install-0vfax9e_/bluepy_94cc612fb75249e39668b35fe40eb5fa
    execute make -C ./bluepy clean
    execute make -C bluepy -j1
    Failed to compile bluepy-helper. Exiting install.
    Command was 'make -C bluepy -j1' in /private/var/folders/57/x0b9lln16kqfwvd_m3xb97rm0000gn/T/pip-install-0vfax9e_/bluepy_94cc612fb75249e39668b35fe40eb5fa
    Return code was 2
    Output was:
    b"tar xzf bluez-src.tgz\nPackage
    glib-2.0 was not found in the pkg-config search path.\nPerhaps you should add the directory containing
    `glib-2.0.pc'\nto the PKG_CONFIG_PATH environment variable\nNo package
    'glib-2.0' found\ntouch ./bluez-5.47/lib/bluetooth.c ./bluez-5.47/lib/hci.c ./bluez-5.47/lib/sdp.c ./bluez-5.47/lib/uuid.c ./bluez-5.47/attrib/att.c ./bluez-5.47/attrib/gatt.c ./bluez-5.47/attrib/gattrib.c ./bluez-5.47/attrib/utils.c ./bluez-5.47/btio/btio.c ./bluez-5.47/src/log.c ./bluez-5.47/src/shared/mgmt.c ./bluez-5.47/src/shared/crypto.c ./bluez-5.47/src/shared/att.c ./bluez-5.47/src/shared/queue.c ./bluez-5.47/src/shared/util.c ./bluez-5.47/src/shared/io-glib.c ./bluez-5.47/src/shared/timeout-glib.c\nPackage glib-2.0 was not found in the pkg-config search path.\nPerhaps you should add the directory containing `glib-2.0.pc'\nto the PKG_CONFIG_PATH environment variable\nNo package 'glib-2.0' found\nPackage glib-2.0 was not found in the pkg-config search path.\nPerhaps you should add the directory containing `glib-2.0.pc'\nto the PKG_CONFIG_PATH environment variable\nNo package 'glib-2.0' found\nx86_64-apple-darwin13.4.0-clang -L. -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -isystem /Users/sebastian/anaconda3/include -g -Wall  -Os -D_FORTIFY_SOURCE=2 -isystem /Users/sebastian/anaconda3/include -DHAVE_CONFIG_H -I./bluez-5.47/attrib -I./bluez-5.47 -I./bluez-5.47/lib -I./bluez-5.47/src -I./bluez-5.47/gdbus -I./bluez-5.47/btio -I./bluez-5.47/sys  -o bluepy-helper bluepy-helper.c ./bluez-5.47/lib/bluetooth.c ./bluez-5.47/lib/hci.c ./bluez-5.47/lib/sdp.c ./bluez-5.47/lib/uuid.c ./bluez-5.47/attrib/att.c ./bluez-5.47/attrib/gatt.c ./bluez-5.47/attrib/gattrib.c ./bluez-5.47/attrib/utils.c ./bluez-5.47/btio/btio.c ./bluez-5.47/src/log.c ./bluez-5.47/src/shared/mgmt.c ./bluez-5.47/src/shared/crypto.c ./bluez-5.47/src/shared/att.c ./bluez-5.47/src/shared/queue.c ./bluez-5.47/src/shared/util.c ./bluez-5.47/src/shared/io-glib.c ./bluez-5.47/src/shared/timeout-glib.c \nPackage glib-2.0 was not found in the pkg-config search path.\nPerhaps you should add the directory containing `glib-2.0.pc'\nto the PKG_CONFIG_PATH environment variable\nNo package 'glib-2.0' found\ndyld[12140]: Library not loaded: @rpath/libclang-cpp.14.dylib\n  Referenced from: <376B7D56-B274-3093-A3AD-428E0CE3DE66> /Users/sebastian/anaconda3/bin/clang-14\n  Reason: tried: '/Users/sebastian/anaconda3/bin/../lib/libclang-cpp.14.dylib' (no such file), '/Users/sebastian/anaconda3/bin/../lib/libclang-cpp.14.dylib' (no such file), '/Users/sebastian/anaconda3/bin/../lib/libclang-cpp.14.dylib' (no such file), '/Users/sebastian/anaconda3/bin/../lib/libclang-cpp.14.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS@rpath/libclang-cpp.14.dylib' (no such file), '/Users/sebastian/anaconda3/bin/../lib/libclang-cpp.14.dylib' (no such file), '/Users/sebastian/anaconda3/bin/../lib/libclang-cpp.14.dylib' (no such file), '/Users/sebastian/anaconda3/bin/../lib/libclang-cpp.14.dylib' (no such file), '/Users/sebastian/anaconda3/bin/../lib/libclang-cpp.14.dylib' (no such file), '/usr/local/lib/libclang-cpp.14.dylib' (no such file), '/usr/lib/libclang-cpp.14.dylib' (no such file, not in dyld cache)\nmake: *** [bluepy-helper] Abort trap: 6\n"
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Users/sebastian/zmk-config-corne-beekeeb/battery_reporter/env/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/57/x0b9lln16kqfwvd_m3xb97rm0000gn/T/pip-install-0vfax9e_/bluepy_94cc612fb75249e39668b35fe40eb5fa/setup.py'"'"'; __file__='"'"'/private/var/folders/57/x0b9lln16kqfwvd_m3xb97rm0000gn/T/pip-install-0vfax9e_/bluepy_94cc612fb75249e39668b35fe40eb5fa/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/57/x0b9lln16kqfwvd_m3xb97rm0000gn/T/pip-record-p4bm7m99/install-record.txt --single-version-externally-managed --compile --install-headers /Users/sebastian/zmk-config-corne-beekeeb/battery_reporter/env/include/site/python3.9/bluepy Check the logs for full command output.
WARNING: You are using pip version 21.2.4; however, version 24.1.2 is available.
You should consider upgrading via the '/Users/sebastian/zmk-config-corne-beekeeb/battery_reporter/env/bin/python3 -m pip install --upgrade pip' command.
(env) (base) sebastian@Juans-MacBook-Pro battery_reporter % pip list
Package    Version
---------- -------
pip        21.2.4
setuptools 58.0.4
WARNING: You are using pip version 21.2.4; however, version 24.1.2 is available.
You should consider upgrading via the '/Users/sebastian/zmk-config-corne-beekeeb/battery_reporter/env/bin/python3 -m pip install --upgrade pip' command.